import type { DockerCommandId } from "./docker-command-registry";

export type AdvancedDockerCommandId =
  | "containers.logsSinceFollow"
  | "containers.execAsRoot"
  | "containers.inspectState"
  | "containers.inspectIp"
  | "containers.port"
  | "containers.statsNoStream"
  | "containers.topAux"
  | "containers.psExited"
  | "containers.psUnhealthy"
  | "containers.psFormat"
  | "containers.updateRestart"
  | "containers.runEntrypointShell"
  | "containers.runNetshootSidecar"
  | "images.historyNoTrunc"
  | "images.inspectDetail"
  | "images.buildNoCachePlain"
  | "images.buildTarget"
  | "images.scoutCves"
  | "compose.logsFollow"
  | "compose.psAll"
  | "compose.config"
  | "compose.exec"
  | "compose.buildNoCache"
  | "compose.upForceRecreate"
  | "networks.inspectFormatContainers"
  | "networks.runDig"
  | "networks.runCurlHealth"
  | "volumes.inspectDetail"
  | "volumes.runDu"
  | "volumes.runBackup"
  | "system.dfVerbose"
  | "builder.prune"
  | "containers.pruneUntil"
  | "images.pruneUntil"
  | "builder.pruneUntil"
  | "compose.downOrphans";

type AdvancedEntry = {
  id: AdvancedDockerCommandId;
  label: string;
  cli: string;
  explanation: string;
  description: string;
  risk: "safe" | "medium" | "destructive";
  category: "containers" | "images" | "volumes" | "networks" | "events" | "general";
  aliases: string[];
  example: string;
  intents: string[];
  relatedIds?: DockerCommandId[];
  whenToUse?: string;
  prerequisites?: string[];
  advanced: true;
  proTip: string;
};

const entry = (data: Omit<AdvancedEntry, "advanced"> & { advanced?: true }): AdvancedEntry => ({
  ...data,
  advanced: true,
});

export const advancedDockerCommandRegistry = {
  "containers.logsSinceFollow": entry({
    id: "containers.logsSinceFollow",
    label: "Tail recent logs",
    cli: "docker logs --since <duration> --tail <n> -f <container>",
    explanation: "Streams only recent log lines instead of the full history.",
    description:
      "Combines --since, --tail, and --follow to focus on what changed recently. Ideal when a container just started failing.",
    risk: "safe",
    category: "containers",
    aliases: ["logs -f", "logs --since", "tail logs"],
    example: "docker logs --since 30m --tail 200 -f my-app",
    intents: ["recent container logs", "follow logs last 30 minutes", "stream failing app logs"],
    relatedIds: ["containers.logs", "containers.inspect"],
    whenToUse: "Use when you need live logs from a recent time window only.",
    prerequisites: ["Container name or ID"],
    proTip: "Cuts noise from old restarts so you spot the actual failure faster.",
  }),
  "containers.execAsRoot": entry({
    id: "containers.execAsRoot",
    label: "Exec as root",
    cli: "docker exec -it -u root <container> sh",
    explanation: "Opens a root shell inside the container for permission fixes.",
    description:
      "Runs an interactive shell as root when the app user cannot read config files or install packages. Prefer read-only debugging first when possible.",
    risk: "medium",
    category: "containers",
    aliases: ["exec root", "exec -u root"],
    example: "docker exec -it -u root my-app sh",
    intents: ["root shell in container", "fix permissions in container"],
    relatedIds: ["containers.exec", "containers.inspect"],
    whenToUse: "Use when permission errors block normal exec debugging.",
    prerequisites: ["Container must be running"],
    proTip: "Saves time when the app runs as a non-root user and hides system paths.",
  }),
  "containers.inspectState": entry({
    id: "containers.inspectState",
    label: "Inspect container state JSON",
    cli: "docker inspect -f '{{json .State}}' <container>",
    explanation: "Prints only the State block as JSON.",
    description: "Shows exit code, OOMKilled, restart count, and health without scrolling through full inspect output.",
    risk: "safe",
    category: "containers",
    aliases: ["inspect state", "inspect -f state"],
    example: "docker inspect -f '{{json .State}}' my-app",
    intents: ["container exit code", "why did container exit", "oom killed"],
    relatedIds: ["containers.inspect", "containers.logs"],
    whenToUse: "Use to quickly see exit code, OOM, and restart count.",
    prerequisites: ["Container name or ID"],
    proTip: "Faster than parsing full inspect when a container keeps restarting.",
  }),
  "containers.inspectIp": entry({
    id: "containers.inspectIp",
    label: "Get container IP addresses",
    cli: "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container>",
    explanation: "Lists IP addresses attached to the container.",
    description: "Useful when debugging service-to-service calls and you need the container IP on a custom network.",
    risk: "safe",
    category: "containers",
    aliases: ["container ip", "inspect ip"],
    example: "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-app",
    intents: ["container ip address", "network ip of container"],
    relatedIds: ["containers.inspect", "networks.inspect"],
    whenToUse: "Use when curl by IP or firewall rules need the container address.",
    prerequisites: ["Container name or ID"],
    proTip: "Handy when DNS works in Compose but you need to verify the actual endpoint.",
  }),
  "containers.port": entry({
    id: "containers.port",
    label: "List published ports",
    cli: "docker port <container>",
    explanation: "Shows host-to-container port mappings.",
    description:
      "Maps container ports to host ports. Confirms whether your app is reachable on localhost and which port to use.",
    risk: "safe",
    category: "containers",
    aliases: ["port mapping", "published ports"],
    example: "docker port my-app",
    intents: ["which port is exposed", "port mapping container"],
    relatedIds: ["containers.listRunning", "containers.inspect"],
    whenToUse: "Use when you cannot reach a service and need to verify published ports.",
    prerequisites: ["Container name or ID"],
    proTip: "Instant answer to “what URL do I hit on the host?”",
  }),
  "containers.statsNoStream": entry({
    id: "containers.statsNoStream",
    label: "One-shot container stats",
    cli: "docker stats --no-stream <container>",
    explanation: "Snapshots CPU and memory once instead of streaming.",
    description: "Returns a single stats row you can paste into tickets or compare before and after a change.",
    risk: "safe",
    category: "containers",
    aliases: ["stats --no-stream", "snapshot stats"],
    example: "docker stats --no-stream my-app",
    intents: ["memory usage snapshot", "cpu usage once", "container resources snapshot"],
    relatedIds: ["containers.stats", "containers.top"],
    whenToUse: "Use when you need a point-in-time resource reading without a live stream.",
    prerequisites: ["Container must be running"],
    proTip: "Better for screenshots and Slack than leaving stats streaming in a terminal.",
  }),
  "containers.topAux": entry({
    id: "containers.topAux",
    label: "Processes with aux format",
    cli: "docker top <container> aux",
    explanation: "Shows processes inside the container with full ps aux columns.",
    description: "Reveals zombie processes, unexpected shells, or runaway workers inside the container namespace.",
    risk: "safe",
    category: "containers",
    aliases: ["top aux", "processes aux"],
    example: "docker top my-app aux",
    intents: ["process list in container", "what is running inside container"],
    relatedIds: ["containers.top", "containers.exec"],
    whenToUse: "Use when the app is hung but logs look normal.",
    prerequisites: ["Container name or ID"],
    proTip: "Often shows a stuck worker or shell that logs never mention.",
  }),
  "containers.psExited": entry({
    id: "containers.psExited",
    label: "List exited containers",
    cli: "docker ps --filter status=exited",
    explanation: "Shows only containers that have stopped.",
    description:
      "Filters docker ps to exited containers so you can find crash-loop victims without noise from running ones.",
    risk: "safe",
    category: "containers",
    aliases: ["ps exited", "filter exited"],
    example: "docker ps --filter status=exited",
    intents: ["list exited containers", "find crashed containers"],
    relatedIds: ["containers.listAll", "containers.inspectState"],
    whenToUse: "Use after deploys to see what failed and is no longer running.",
    prerequisites: ["Docker Engine running"],
    proTip: "Much faster than scanning docker ps -a during incident triage.",
  }),
  "containers.psUnhealthy": entry({
    id: "containers.psUnhealthy",
    label: "List unhealthy containers",
    cli: "docker ps --filter health=unhealthy",
    explanation: "Shows containers failing their health check.",
    description: "Surfaces services that are running but not passing HEALTHCHECK, common in Compose stacks.",
    risk: "safe",
    category: "containers",
    aliases: ["unhealthy containers", "health filter"],
    example: "docker ps --filter health=unhealthy",
    intents: ["unhealthy containers", "healthcheck failing"],
    relatedIds: ["containers.listRunning", "containers.logs"],
    whenToUse: "Use when the stack is up but load balancers or probes fail.",
    prerequisites: ["Containers with HEALTHCHECK defined"],
    proTip: "Finds “green in ps but red in monitoring” cases in one command.",
  }),
  "containers.psFormat": entry({
    id: "containers.psFormat",
    label: "Custom ps table",
    cli: "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
    explanation: "Prints a compact custom table of names, status, and ports.",
    description: "Go template formatting keeps output readable in narrow terminals and when sharing status in chat.",
    risk: "safe",
    category: "containers",
    aliases: ["ps --format", "custom ps output"],
    example: "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'",
    intents: ["formatted container list", "ps table names ports"],
    relatedIds: ["containers.listRunning", "containers.port"],
    whenToUse: "Use when default ps columns are too wide or missing what you need.",
    prerequisites: ["Docker Engine running"],
    proTip: "Build your own incident dashboard columns once and reuse the format.",
  }),
  "containers.updateRestart": entry({
    id: "containers.updateRestart",
    label: "Set restart policy",
    cli: "docker update --restart unless-stopped <container>",
    explanation: "Changes restart policy on an existing container.",
    description: "Applies unless-stopped so Docker restarts the container after daemon reboot without recreating it.",
    risk: "medium",
    category: "containers",
    aliases: ["update restart", "restart unless-stopped"],
    example: "docker update --restart unless-stopped my-app",
    intents: ["restart policy", "auto restart container"],
    relatedIds: ["containers.run", "containers.restart"],
    whenToUse: "Use after docker run without --restart when you want daemon-level resilience.",
    prerequisites: ["Container name or ID"],
    proTip: "Fixes “it died overnight” without rebuilding the container.",
  }),
  "containers.runEntrypointShell": entry({
    id: "containers.runEntrypointShell",
    label: "Debug image with shell entrypoint",
    cli: "docker run --rm -it --entrypoint sh <image>",
    explanation: "Starts a throwaway container with shell instead of the default command.",
    description:
      "Overrides entrypoint to sh so you can explore the image filesystem and test binaries without the app starting.",
    risk: "medium",
    category: "containers",
    aliases: ["run --entrypoint", "debug image shell"],
    example: "docker run --rm -it --entrypoint sh nginx:alpine",
    intents: ["shell into image", "debug dockerfile", "test image without app"],
    relatedIds: ["images.pull", "containers.run"],
    whenToUse: "Use to verify what is inside an image before wiring it into Compose.",
    prerequisites: ["Image available locally or pullable"],
    proTip: "Classic lifesaver when the main process exits immediately on start.",
  }),
  "containers.runNetshootSidecar": entry({
    id: "containers.runNetshootSidecar",
    label: "Network debug sidecar",
    cli: "docker run --rm --network container:<container> nicolaka/netshoot ss -tulpn",
    explanation: "Runs netshoot in the target container network namespace.",
    description:
      "Shares another container's network stack to inspect listening ports and connectivity with proper tools (ss, dig, curl).",
    risk: "medium",
    category: "containers",
    aliases: ["netshoot", "network sidecar", "container network debug"],
    example: "docker run --rm --network container:my-app nicolaka/netshoot ss -tulpn",
    intents: ["debug container network", "netshoot sidecar", "ports listening in container"],
    relatedIds: ["containers.inspectIp", "networks.runDig"],
    whenToUse: "Use when the app image lacks dig/curl/ss but networking is suspect.",
    prerequisites: ["Target container running", "Pulls nicolaka/netshoot on first use"],
    proTip: "Avoids installing debug tools into production images permanently.",
  }),
  "images.historyNoTrunc": entry({
    id: "images.historyNoTrunc",
    label: "Image history (full commands)",
    cli: "docker image history --no-trunc <image>",
    explanation: "Shows full Dockerfile layer commands without truncation.",
    description: "Reveals exact RUN lines and layer sizes when debugging bloated images or unexpected binaries.",
    risk: "safe",
    category: "images",
    aliases: ["history --no-trunc", "image layers full"],
    example: "docker image history --no-trunc my-app:latest",
    intents: ["image layer history", "why is image so big", "dockerfile layers"],
    relatedIds: ["images.build", "images.inspectDetail"],
    whenToUse: "Use when docker history truncates commands you need to read.",
    prerequisites: ["Image name:tag or ID"],
    proTip: "Often exposes a forgotten COPY or apt-get layer instantly.",
  }),
  "images.inspectDetail": entry({
    id: "images.inspectDetail",
    label: "Inspect image metadata",
    cli: "docker image inspect <image>",
    explanation: "Returns full JSON metadata for one image.",
    description: "Shows config, env defaults, exposed ports, and rootfs layers. Use before running mystery images.",
    risk: "safe",
    category: "images",
    aliases: ["image inspect"],
    example: "docker image inspect my-app:latest",
    intents: ["inspect image", "image metadata", "image env defaults"],
    relatedIds: ["images.historyNoTrunc", "images.list"],
    whenToUse: "Use to verify entrypoint, env, and exposed ports before deploy.",
    prerequisites: ["Image name:tag or ID"],
    proTip: "Confirms what the container will actually run without starting it.",
  }),
  "images.buildNoCachePlain": entry({
    id: "images.buildNoCachePlain",
    label: "Clean rebuild with plain logs",
    cli: "docker build --no-cache --progress=plain -t <tag> .",
    explanation: "Rebuilds from scratch with verbose plain-text build output.",
    description:
      "Disables cache and shows every build step clearly—best when a cached layer hides a failing RUN command.",
    risk: "medium",
    category: "images",
    aliases: ["build --no-cache", "build plain progress"],
    example: "docker build --no-cache --progress=plain -t my-app:debug .",
    intents: ["rebuild without cache", "debug docker build", "plain build output"],
    relatedIds: ["images.build", "images.buildTarget"],
    whenToUse: "Use when CI passes locally fails or cache masks Dockerfile changes.",
    prerequisites: ["Dockerfile in build context"],
    proTip: "The first command to run when “it worked yesterday” on image builds.",
  }),
  "images.buildTarget": entry({
    id: "images.buildTarget",
    label: "Build specific stage",
    cli: "docker build --target <stage> -t <tag> .",
    explanation: "Builds only up to a named multi-stage target.",
    description: "Stops at a Dockerfile stage (e.g. test or builder) without producing the final production image.",
    risk: "medium",
    category: "images",
    aliases: ["build --target", "multi-stage build"],
    example: "docker build --target test -t my-app:test .",
    intents: ["build test stage", "multi-stage dockerfile", "build intermediate stage"],
    relatedIds: ["images.build", "images.buildNoCachePlain"],
    whenToUse: "Use to iterate on a single stage in multi-stage Dockerfiles.",
    prerequisites: ["Named stage in Dockerfile"],
    proTip: "Speeds up Dockerfile refactors by skipping unrelated final stages.",
  }),
  "images.scoutCves": entry({
    id: "images.scoutCves",
    label: "Scan image for CVEs (Scout)",
    cli: "docker scout cves <image>",
    explanation: "Scans an image for known vulnerabilities with Docker Scout.",
    description: "Requires Docker Scout CLI integration. Reports CVEs in base images and dependencies before deploy.",
    risk: "safe",
    category: "images",
    aliases: ["scout cves", "vulnerability scan"],
    example: "docker scout cves my-app:latest",
    intents: ["scan image vulnerabilities", "docker scout", "cve scan"],
    relatedIds: ["images.inspectDetail", "images.pull"],
    whenToUse: "Use in CI or before promoting an image to production.",
    prerequisites: ["Docker Scout available", "Image built or pulled"],
    proTip: "Catches base-image CVEs that never show up in app-level tests.",
  }),
  "compose.logsFollow": entry({
    id: "compose.logsFollow",
    label: "Compose service logs (follow)",
    cli: "docker compose logs --tail <n> -f <service>",
    explanation: "Tails logs for one Compose service.",
    description:
      "Streams logs for a single service in the stack—faster than reading every container in a busy project.",
    risk: "safe",
    category: "general",
    aliases: ["compose logs -f"],
    example: "docker compose logs --tail 100 -f api",
    intents: ["compose service logs", "follow api logs"],
    relatedIds: ["compose.ps", "containers.logs"],
    whenToUse: "Use when one service fails in a multi-service compose file.",
    prerequisites: ["docker-compose.yml in current directory", "Service name"],
    proTip: "Narrows multi-container noise to the service you actually care about.",
  }),
  "compose.psAll": entry({
    id: "compose.psAll",
    label: "Compose ps (including stopped)",
    cli: "docker compose ps --all",
    explanation: "Lists all project containers including exited ones.",
    description: "Shows stopped and exited compose services—essential when a service crashed during up.",
    risk: "safe",
    category: "general",
    aliases: ["compose ps -a", "compose ps all"],
    example: "docker compose ps --all",
    intents: ["compose exited services", "all compose containers"],
    relatedIds: ["compose.ps", "compose.up"],
    whenToUse: "Use when compose up succeeded but a service is missing from default ps.",
    prerequisites: ["Compose project in current directory"],
    proTip: "Finds the one-shot migration container that exited and took the stack down.",
  }),
  "compose.config": entry({
    id: "compose.config",
    label: "Validate compose file",
    cli: "docker compose config",
    explanation: "Renders the effective compose configuration.",
    description:
      "Expands env files and shows the final YAML Docker Compose will use. Catches typos and wrong service names before up.",
    risk: "safe",
    category: "general",
    aliases: ["compose config"],
    example: "docker compose config",
    intents: ["validate compose file", "compose config check"],
    relatedIds: ["compose.up", "compose.ps"],
    whenToUse: "Use before compose up when env substitution or merges look wrong.",
    prerequisites: ["docker-compose.yml in current directory"],
    proTip: "Catches “service not found” and env typos without starting anything.",
  }),
  "compose.exec": entry({
    id: "compose.exec",
    label: "Compose exec into service",
    cli: "docker compose exec <service> sh",
    explanation: "Runs a command in a running compose service container.",
    description:
      "Uses the project context so you do not need the generated container name—just the service name from the compose file.",
    risk: "medium",
    category: "general",
    aliases: ["compose exec"],
    example: "docker compose exec api sh",
    intents: ["shell into compose service", "compose exec api"],
    relatedIds: ["containers.exec", "compose.ps"],
    whenToUse: "Use to debug inside a service without looking up container IDs.",
    prerequisites: ["Service running", "Compose project directory"],
    proTip: "Service names beat memorizing compose-prefixed container names.",
  }),
  "compose.buildNoCache": entry({
    id: "compose.buildNoCache",
    label: "Compose rebuild service",
    cli: "docker compose build --no-cache <service>",
    explanation: "Rebuilds one service image without cache.",
    description: "Forces a fresh image build for a single service in the stack—faster than rebuilding everything.",
    risk: "medium",
    category: "general",
    aliases: ["compose build --no-cache"],
    example: "docker compose build --no-cache api",
    intents: ["rebuild compose service", "no cache compose build"],
    relatedIds: ["compose.up", "images.buildNoCachePlain"],
    whenToUse: "Use when one service Dockerfile changed but others are fine.",
    prerequisites: ["Service defined with build context"],
    proTip: "Saves minutes versus nuking the entire compose build cache.",
  }),
  "compose.upForceRecreate": entry({
    id: "compose.upForceRecreate",
    label: "Recreate one service",
    cli: "docker compose up -d --force-recreate <service>",
    explanation: "Recreates containers for a service even if config unchanged.",
    description:
      "Picks up new images or env changes that would not trigger a normal up. Brief downtime for that service.",
    risk: "medium",
    category: "general",
    aliases: ["compose up --force-recreate"],
    example: "docker compose up -d --force-recreate api",
    intents: ["recreate compose service", "force new container"],
    relatedIds: ["compose.up", "compose.buildNoCache"],
    whenToUse: "Use when the image tag stayed the same but content changed.",
    prerequisites: ["Compose project in current directory"],
    proTip: "Fixes “I pushed :latest but nothing changed” without downing the stack.",
  }),
  "networks.inspectFormatContainers": entry({
    id: "networks.inspectFormatContainers",
    label: "Network attached containers",
    cli: "docker network inspect <network> --format '{{json .Containers}}'",
    explanation: "Lists containers attached to a network as JSON.",
    description: "Shows which containers are on a network and their endpoints—key for “cannot connect to api” issues.",
    risk: "safe",
    category: "networks",
    aliases: ["network containers json"],
    example: "docker network inspect my-net --format '{{json .Containers}}'",
    intents: ["containers on network", "who is on this network"],
    relatedIds: ["networks.inspect", "networks.runDig"],
    whenToUse: "Use when services should talk on a custom network but DNS fails.",
    prerequisites: ["Network name"],
    proTip: "Proves whether the client container is actually attached to the right network.",
  }),
  "networks.runDig": entry({
    id: "networks.runDig",
    label: "DNS lookup from network",
    cli: "docker run --rm --network <network> nicolaka/netshoot dig <host>",
    explanation: "Runs dig on a custom network to test service DNS.",
    description: "Starts a throwaway netshoot container on the same network to resolve another service name.",
    risk: "medium",
    category: "networks",
    aliases: ["netshoot dig", "dns docker network"],
    example: "docker run --rm --network my-net nicolaka/netshoot dig api",
    intents: ["dns lookup docker", "can resolve service name", "dig api compose"],
    relatedIds: ["networks.inspectFormatContainers", "networks.runCurlHealth"],
    whenToUse: "Use when containers cannot resolve each other by service name.",
    prerequisites: ["Network exists", "Pulls nicolaka/netshoot on first use"],
    proTip: "Separates DNS problems from application bugs in under a minute.",
  }),
  "networks.runCurlHealth": entry({
    id: "networks.runCurlHealth",
    label: "HTTP health check from network",
    cli: "docker run --rm --network <network> nicolaka/netshoot curl -v <url>",
    explanation: "Runs curl from inside the Docker network toward a service URL.",
    description:
      "Tests HTTP connectivity the same way another container would—includes TLS and redirect details with -v.",
    risk: "medium",
    category: "networks",
    aliases: ["netshoot curl", "health check from network"],
    example: "docker run --rm --network my-net nicolaka/netshoot curl -v http://api:3000/health",
    intents: ["curl service from network", "health endpoint docker", "test api connectivity"],
    relatedIds: ["networks.runDig", "containers.port"],
    whenToUse: "Use when the app listens but another service gets connection refused.",
    prerequisites: ["Network exists", "Target URL reachable on that network"],
    proTip: "Reproduces “works on host, fails container-to-container” faithfully.",
  }),
  "volumes.inspectDetail": entry({
    id: "volumes.inspectDetail",
    label: "Inspect volume",
    cli: "docker volume inspect <volume>",
    explanation: "Shows mountpoint and driver details for a volume.",
    description: "Confirms which volume name maps to which host path before backup or cleanup.",
    risk: "safe",
    category: "volumes",
    aliases: ["volume inspect"],
    example: "docker volume inspect my-data",
    intents: ["inspect volume", "volume mountpoint"],
    relatedIds: ["volumes.list", "volumes.runDu"],
    whenToUse: "Use before backup or prune when multiple similarly named volumes exist.",
    prerequisites: ["Volume name"],
    proTip: "Avoids backing up the wrong volume when names differ by one character.",
  }),
  "volumes.runDu": entry({
    id: "volumes.runDu",
    label: "Measure volume size",
    cli: "docker run --rm -v <volume>:/data alpine du -sh /data",
    explanation: "Reports disk usage inside a named volume.",
    description:
      "Mounts the volume into a throwaway alpine container and runs du. No need to know the host mount path.",
    risk: "medium",
    category: "volumes",
    aliases: ["volume size", "du volume"],
    example: "docker run --rm -v my-data:/data alpine du -sh /data",
    intents: ["how big is volume", "volume disk usage"],
    relatedIds: ["volumes.inspectDetail", "system.dfVerbose"],
    whenToUse: "Use when disk is full and you suspect a specific volume.",
    prerequisites: ["Volume name", "Pulls alpine on first use"],
    proTip: "Answers “which volume ate my disk?” without SSH to the host path.",
  }),
  "volumes.runBackup": entry({
    id: "volumes.runBackup",
    label: "Backup volume to tarball",
    cli: "docker run --rm -v <volume>:/data -v <backup-dir>:/backup alpine tar czf /backup/<file>.tgz -C /data .",
    explanation: "Archives volume contents to a tarball on the host.",
    description:
      "Creates a portable backup without stopping the main container. Overwrites the archive file if it already exists.",
    risk: "destructive",
    category: "volumes",
    aliases: ["backup volume", "tar volume"],
    example: "docker run --rm -v my-data:/data -v ./backup:/backup alpine tar czf /backup/my-data.tgz -C /data .",
    intents: ["backup docker volume", "export volume data"],
    relatedIds: ["volumes.runDu", "volumes.inspectDetail"],
    whenToUse: "Use before risky migrations or volume prune.",
    prerequisites: ["Backup directory exists on host", "Enough disk space for archive"],
    proTip: "Lifesaver before compose down -v or moving Postgres between hosts.",
  }),
  "system.dfVerbose": entry({
    id: "system.dfVerbose",
    label: "Verbose disk usage",
    cli: "docker system df -v",
    explanation: "Shows per-object disk usage breakdown.",
    description: "Lists each image, container, and volume with size—more detail than plain docker system df.",
    risk: "safe",
    category: "general",
    aliases: ["system df -v", "df verbose"],
    example: "docker system df -v",
    intents: ["what is using docker disk", "verbose df docker"],
    relatedIds: ["system.df", "images.prune"],
    whenToUse: "Use when you need to find the specific object consuming space.",
    prerequisites: ["Docker Engine running"],
    proTip: "Turns “Docker is using 40GB” into an actionable hit list.",
  }),
  "builder.prune": entry({
    id: "builder.prune",
    label: "Prune build cache",
    cli: "docker builder prune -f",
    explanation: "Removes unused build cache.",
    description:
      "Frees space from BuildKit/cache layers not used by current images. Safe relative to image prune but can slow next builds.",
    risk: "destructive",
    category: "general",
    aliases: ["builder prune"],
    example: "docker builder prune -f",
    intents: ["clear build cache", "free buildkit cache"],
    relatedIds: ["system.dfVerbose", "images.build"],
    whenToUse: "Use when builds work but disk is full from old cache layers.",
    prerequisites: ["Understand next builds may be slower"],
    proTip: "Often recovers gigabytes CI machines hide in build cache.",
  }),
  "containers.pruneUntil": entry({
    id: "containers.pruneUntil",
    label: "Prune old stopped containers",
    cli: "docker container prune --filter until=24h",
    explanation: "Removes stopped containers older than the filter window.",
    description: "Safer than blanket prune—only containers stopped for more than the until duration are removed.",
    risk: "destructive",
    category: "containers",
    aliases: ["container prune until"],
    example: "docker container prune --filter until=24h",
    intents: ["prune old containers", "cleanup exited containers"],
    relatedIds: ["containers.psExited", "system.prune"],
    whenToUse: "Use for scheduled cleanup without deleting recent exited debug containers.",
    prerequisites: ["Review filter duration before confirming"],
    proTip: "Safer default than pruning every stopped container on a busy dev machine.",
  }),
  "images.pruneUntil": entry({
    id: "images.pruneUntil",
    label: "Prune old unused images",
    cli: "docker image prune --filter until=168h",
    explanation: "Removes dangling images older than the filter window.",
    description:
      "Targets old dangling layers while leaving recent build artifacts. Add -a carefully for all unused images.",
    risk: "destructive",
    category: "images",
    aliases: ["image prune until"],
    example: "docker image prune --filter until=168h",
    intents: ["prune old images", "cleanup dangling images"],
    relatedIds: ["images.prune", "system.dfVerbose"],
    whenToUse: "Use for weekly cleanup without wiping images you built today.",
    prerequisites: ["Understand dangling vs unused (-a)"],
    proTip: "Keeps dev machines from becoming image graveyards over time.",
  }),
  "builder.pruneUntil": entry({
    id: "builder.pruneUntil",
    label: "Prune old build cache",
    cli: "docker builder prune --filter until=24h",
    explanation: "Removes build cache older than the filter window.",
    description: "More conservative than builder prune -f—drops stale cache while keeping recent layers for speed.",
    risk: "destructive",
    category: "general",
    aliases: ["builder prune until"],
    example: "docker builder prune --filter until=24h",
    intents: ["prune old build cache"],
    relatedIds: ["builder.prune", "images.buildNoCachePlain"],
    whenToUse: "Use when you want disk back but keep yesterday's cache warm.",
    prerequisites: ["BuildKit enabled"],
    proTip: "Balance between docker builder prune -f and never cleaning cache.",
  }),
  "compose.downOrphans": entry({
    id: "compose.downOrphans",
    label: "Compose down with orphans",
    cli: "docker compose down --remove-orphans",
    explanation: "Stops the stack and removes containers not in the compose file.",
    description: "Cleans up leftover containers from renamed services or old compose files—common after refactors.",
    risk: "destructive",
    category: "general",
    aliases: ["compose down orphans", "remove orphans"],
    example: "docker compose down --remove-orphans",
    intents: ["remove orphan containers", "clean compose stack"],
    relatedIds: ["compose.down", "compose.psAll"],
    whenToUse: "Use after renaming services or switching branches with different compose files.",
    prerequisites: ["Compose project in current directory"],
    proTip: "Fixes mystery containers still binding ports after a service rename.",
  }),
} as const satisfies Record<AdvancedDockerCommandId, AdvancedEntry>;

export const advancedDockerCommandList: AdvancedEntry[] = Object.values(advancedDockerCommandRegistry);
